# Generated by Django 4.2 on 2025-10-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_subregistraroffice_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Home.subregistraroffice'),
        ),
    ]
