# Generated by Django 4.2 on 2025-10-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_transaction_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.subregistraroffice'),
        ),
    ]
