# Generated by Django 4.2 on 2025-10-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customer_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Home.subregistraroffice'),
        ),
    ]
