# Generated by Django 4.2 on 2025-12-30 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_transaction_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eth_address',
            field=models.CharField(blank=True, help_text="Resident's Ethereum wallet (0x...)", max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_eth',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('outbound', 'Resident Sends ETH'), ('inbound', 'Resident Receives ETH')], default='outbound', help_text='Whether the resident is sending or receiving ETH', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
