# Generated by Django 4.2 on 2026-01-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_customer_eth_address_transaction_amount_eth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
