# Generated by Django 4.2 on 2025-10-03 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregistraroffice',
            name='district',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subregistraroffice',
            name='locality',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
