# Generated by Django 4.2 on 2026-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_transaction_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
